name: Update Purelymail Swagger Spec

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions: {}

jobs:
  update-spec:
    name: update swagger spec
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for commit/PR
      pull-requests: write # Needed for commenting

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0

      - name: Run spec fetch script
        run: get_spec

      - name: Check for changes
        id: git-diff
        run: |
          if git status --porcelain | grep 'spec.jsonc'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          commit-message: "chore: update swagger spec"
          title: "chore: update Swagger spec"
          body: |
            ### ğŸš¨ The Swagger spec has changed. ğŸš¨

            Please review the updates to `spec.json` and update collection accordingly.
          branch: update-swagger-spec
          base: main
          delete-branch: true

      - name: Post or update reminder comment
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'true'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: purelymail-spec-check
          mode: upsert
          message: |
            ### ğŸš¨ **Reminder:** Your Purelymail API spec isn't up-to-date. ğŸš¨

            Please run the `bin/get_spec` script and commit the updated spec.
            Don't forget to update your code to reflect this API update!

      - name: Delete reminder comment when fixed
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'false'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: purelymail-spec-check
          mode: delete

      - name: Fail if reminder was posted
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'true'
        run: |
          echo "::error::âŒ Spec is out of date. Please update it using bin/get_spec."
          exit 1
