name: Update Purelymail Swagger Spec

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions: {}

jobs:
  update-spec:
    name: update swagger spec
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for commit/PR
      pull-requests: write # Needed for commenting

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      - name: Run spec fetch script
        run: get_spec

      - name: Check for changes
        id: git-diff
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "chore: update swagger spec"
          title: "chore: update Swagger spec"
          body: |
            ### ğŸš¨ The Swagger spec has changed. ğŸš¨

            Please review the updates to `spec.json` and update collection accordingly.
          branch: update-swagger-spec
          base: main
          delete-branch: true

      - name: Post or update reminder comment
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'true'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        with:
          comment-tag: purelymail-spec-check
          mode: upsert
          message: |
            ### ğŸš¨ **Reminder:** Your Purelymail API spec isn't up-to-date. ğŸš¨

            Please run the `bin/get_spec` script and commit the updated spec.
            Don't forget to update your code to reflect this API update!

      - name: Delete reminder comment when fixed
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'false'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
        with:
          comment-tag: purelymail-spec-check
          mode: delete

      - name: Fail if reminder was posted
        if: github.event_name == 'pull_request' && steps.git-diff.outputs.changed == 'true'
        run: |
          echo "::error::âŒ Spec is out of date. Please update it using bin/get_spec."
          exit 1
